### ISSUE TITLE
maximum number of  committed subtransactions (268435455) exceeded

### ISSUE THREAD

**Issue by sercoin** [woodbri/osrm-tools#8]
Hi,

I get this error while I running pgr_CreateTopology function. Can you explain that? And Is there any solution for that?

Regards.

**Comment by woodbri** [comment]
This is a new one to me. And google is not very helpful either on this. This is actually a Postgresql error message. I suspect that it is caused because stored procedures are run inside a transaction that is completed only when the function exits. I'm guessing other things that happen in the stored procedure are creating subtransactions. But I'm not aware of anything that we are doing like recursing calls that might cause this to pile up and hit this limit.

This ticket should probably be in the pgrouting or postgresql ticket systems as I don;t think it is directly related to osrm-tools. And my answer above applies to the pgrouting.
